plugin-version: 1.0.0
schematics-folder: "plugins/WorldEdit/schematics"
countdown:
    seconds: 60
game:
    min-players: 2
    max-players: 16
    player-health-points: 8
    water-bombs: 3
chat-prefix:
    alive: "%team-color%<%player%>&r"
    dead: "&7Dead %team-color%<%player%>&r"
kit-settings:
    rifle:
        bullet-dmg: 3
        bullet-speed: 3.0
        bullet-spread: 0.01
        player-speed: 1
    shotgun:
        bullet-count: 6
        bullet-dmg: 1
        bullet-speed: 1.25
        bullet-spread: 0.35
        player-speed: 1
    machine-gun:
        bullet-dmg: 1
        bullet-speed: 2.25
        max-bullet-spread: 0.2
        player-speed: 1
command-triggers:
    game-end-commands: []
    player-win-commands: []
    player-lose-commands: []